name: cpp_final_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.10.0
  country_code_picker: ^3.0.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.17+1
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.0.15
  # printing: ^5.11.0
  pinput: ^3.0.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CppIcons
      fonts:
        - asset: assets/fonts/CppIcons.ttf
  
  assets:
    - assets/
    - assets/onboarding/
    - assets/chat/
    - assets/home/
    - assets/nav-icon/
    - assets/profile/
    - assets/project/
    - assets/contact/
    - assets/payment/
    - assets/courses/
    # - assets/policy.pdf
    - assets/data/
    - assets/images/
    - assets/images/C/
    - assets/images/C++/
    - assets/icons/
    - assets/markdown/
    - assets/markdown/class1/
    - assets/markdown/class2/
    - assets/markdown/class3/
    - assets/markdown/class4/
    - assets/markdown/class5/
    - assets/markdown/class6/
    - assets/markdown/class7/
    - assets/markdown/class8/
    - assets/markdown/class9/
    - assets/markdown/class10/
    - assets/markdown/class11/
    - assets/markdown/class12/
    - assets/markdown/class13/
    - assets/markdown/class14/
    - assets/ctutorial/
    - assets/ctutorial/class1/
    - assets/ctutorial/class2/
    - assets/ctutorial/class3/
    - assets/ctutorial/class4/
    - assets/ctutorial/class5/
    - assets/ctutorial/class6/
    - assets/ctutorial/class7/
    - assets/ctutorial/class8/
    - assets/ctutorial/class9/
    - assets/ctutorial/class10/
    - assets/ctutorial/class11/
    - assets/ctutorial/class12/
    - assets/ctutorial/class13/
    - assets/ctutorial/class14/
    - assets/ctutorial/class15/
    - assets/ctutorial/class16/

