name: cpp_final_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  get: ^4.6.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.9
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.0.15
  rive: ^0.7.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CppIcons
      fonts:
        - asset: assets/fonts/CppIcons.ttf
  
  assets:
    - assets/
    - assets/onboarding/
    - assets/chat/
    - assets/home/
    - assets/nav-icon/
    - assets/profile/
    - assets/project/
    - assets/contact/
    - assets/payment/

