// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi7Fgcsr10dxPRwDkl59Ixd8A14HnEfgU',
    appId: '1:721268082400:web:65f66f137a87c8c4acb285',
    messagingSenderId: '721268082400',
    projectId: 'c-cpp-programming',
    authDomain: 'c-cpp-programming.firebaseapp.com',
    storageBucket: 'c-cpp-programming.appspot.com',
    measurementId: 'G-MKS2GR3MJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZba-Qdl7sv2WP8T3AJ0bvxWjbX5Qqbw',
    appId: '1:721268082400:android:59d54126268e1c6cacb285',
    messagingSenderId: '721268082400',
    projectId: 'c-cpp-programming',
    storageBucket: 'c-cpp-programming.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBesOtJOJVUXNM_SgM2q7dhPk_RlcMpWYo',
    appId: '1:721268082400:ios:e859f29f8d23317cacb285',
    messagingSenderId: '721268082400',
    projectId: 'c-cpp-programming',
    storageBucket: 'c-cpp-programming.appspot.com',
    iosClientId: '721268082400-gvsjba87t0563860f6412gcd6ud8lr9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.cppFinalApp',
  );
}
