// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Mhs3BoUMZsd7fyj_E5Txleo8XM6NBuE',
    appId: '1:397443535473:web:0c3d540a159b09d44201d0',
    messagingSenderId: '397443535473',
    projectId: 'c-cpp-programming-app',
    authDomain: 'c-cpp-programming-app.firebaseapp.com',
    storageBucket: 'c-cpp-programming-app.appspot.com',
    measurementId: 'G-TW26L7PE09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUKzmoIsNThY-ho2Q6eWDx0R_ca9Tt-Lc',
    appId: '1:397443535473:android:213229a0bba1137c4201d0',
    messagingSenderId: '397443535473',
    projectId: 'c-cpp-programming-app',
    storageBucket: 'c-cpp-programming-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQYctNnR65f-nzqaPwrSC_14cO99_s1w',
    appId: '1:397443535473:ios:23d39612dbcc52234201d0',
    messagingSenderId: '397443535473',
    projectId: 'c-cpp-programming-app',
    storageBucket: 'c-cpp-programming-app.appspot.com',
    iosClientId: '397443535473-8i5mi6v6tprujgl3g5svgab8emp970dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cppFinalApp',
  );
}
